#debug模式，true输出控制台日志，false只输出文件日志.生产环境需要关闭debug，rbatis也需移除"debug_mode"
debug: true
is_demo: true
#名称
server_name: "cassieWeb"
#server 地址
server:
  host: "0.0.0.0"
  port: "9999"
  ws: "20003"
#缓存介质类型,"redis"
cache_type: "redis"
#redis地址(cache_type为“redis”时有效)
redis_url: "redis://127.0.0.1:6379"
mongodb_url: "mongodb://localhost:27017"
#数据库地址
database_url: "mysql://root:root@localhost:3306/rivet_admin"
#sqlite数据库地址：
sqlitebase_url: "sqlite://target/cassie.db3"

#逻辑删除字段
logic_column: "del"
logic_un_deleted: 0
logic_deleted: 1
#日志文件存放目录
log_dir: "target/logs/"
#日志分割尺寸-单位KB,MB,GB
log_temp_size: "100MB"
#日志打包格式可选“”（空-不压缩）“gzip”（gz压缩包）“zip”（zip压缩包）“lz4”（lz4压缩包（非常快））
log_pack_compress: "zip"
#日志滚动保留-保留全部: All,按时间保留(秒): KeepTime(i64),按版本保留: KeepNum(i64)
log_rolling_type: "KeepNum(20)"
#日志等级-info,error,warn,debug,trace
log_level: "info"
#JwtToken秘钥
jwt_secret: "cassie_admin"
#短信通道缓存（系统先把数据放入队列sms:send:，第三方短信sdk或程序需要从队列获取并发送，获得回执存入sms:resp:*）,格式为sms:send:手机号和sms:resp:手机号
sms_cache_send_key_prefix: "sms:send:"
#登陆失败拒绝策略，重试次数限制(0次无限制)
login_fail_retry: 3
#登陆失败重试次数限制超过后提示的等待时间（秒）
login_fail_retry_wait_sec: 30
#nacos注册中心核心配置
nacos:
  nacos_flag: false
  nacos_server: "http://127.0.0.1:8848/nacos"
  application_name: "cassie_admin"

#小程序配置
wxapp:
  appid: "wx726d55ff001bf506"
  secret: "407659215044413ef53fcf67b0690ac0"

#api超级管理员id直接跳过api权限
super_admin_ids:
  - "1"
#上传默认实现
upload_type: "OSS"
oss:
  key_id: "LTAI5tARCXTX2k7zHw3o7JqW"
  key_secret: "ap2FgB9cKPq3e2Ot59IlIULRYrScYY"
  endpoint: "oss-cn-beijing.aliyuncs.com"
  bucket: "rivet"
  access_endpoint: "http://rivet.oss-cn-beijing.aliyuncs.com"
#租户化配置    
tenant:
  enable: true   #enable:true 开启租户化
  column: "agency_code"   #column租户化字段
  ignore_table:    #ignore_table 忽略的表
    - "sys_log_login"
    - "sys_log_operation"
    - "sys_user"
