[package]
name = "cassie_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"
[dependencies]
#serde and json
serde_yaml = "0.9.13"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
getset = "0.1.2"